#=======================================================================================================================
         project(platforms-module LANGUAGES CXX)
#=======================================================================================================================
     add_library(platforms-module)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(input)
#=======================================================================================================================
add_subdirectory(windows)
#=======================================================================================================================