#=======================================================================================================================
         project(platforms_module VERSION 0.0.2 LANGUAGES CXX)
#=======================================================================================================================
     add_library(platforms_module)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(windows)
#=======================================================================================================================